<?php echo $this->getContent(); ?>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Group</th>
      <th>Order ID</th>
      <th>Pal cov</th>
      <th>Date</th>
      <th>Customer order</th>
      <th>Type</th>
      <th>Set</th>
      <th>Quantity</th>
      <th>Width</th>
      <th>Length</th>
      <th>Barcode</th>
      <th>Delivery date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($items as $item) { ?>
      <tr>
        <td><?php echo $item['group']; ?></td>
        <td><?php echo $item['order_id']; ?></td>
        <td><?php echo $item['pal_cov']; ?></td>
        <td><?php echo $item['date']; ?></td>
        <td><?php echo $item['customer_order']; ?></td>
        <td><?php echo $item['type']; ?></td>
        <td><?php echo $item['set']; ?></td>
        <td><?php echo $item['quantity']; ?></td>
        <td><?php echo $item['width']; ?></td>
        <td><?php echo $item['length']; ?></td>
        <td><?php echo $item['barcode']; ?></td>
        <td><?php echo $item['delivery_date']; ?></td>
        <td>
          <?php echo $this->tag->linkTo(['export/exportSingle/' .
            $item['id'], ' Export', 'class' => 'btn btn-xs btn-success']); ?>
        </td>
      </tr>
    <?php } ?>
  </tbody>
</table>
