<?php echo $this->getContent(); ?>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td>Group</td>
      <td>Order ID</td>
      <td>Pal cov</td>
      <td>Date</td>
      <td>Customer order</td>
      <td>Type</td>
      <td>Set</td>
      <td>Quantity</td>
      <td>Width</td>
      <td>Length</td>
      <td>Barcode</td>
      <td>Delivery date</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($items as $item) { ?>
      <tr>
        <td><?php echo $item['group']; ?></td>
        <td><?php echo $item['order_id']; ?></td>
        <td><?php echo $item['pal_cov']; ?></td>
        <td><?php echo $item['date']; ?></td>
        <td><?php echo $item['customer_order']; ?></td>
        <td><?php echo $item['type']; ?></td>
        <td><?php echo $item['set']; ?></td>
        <td><?php echo $item['quantity']; ?></td>
        <td><?php echo $item['width']; ?></td>
        <td><?php echo $item['length']; ?></td>
        <td><?php echo $item['barcode']; ?></td>
        <td><?php echo $item['delivery_date']; ?></td>
        <td>
          <?php echo $this->tag->linkTo(['export/exportSingle/' .
            $item['id'], ' Export', 'class' => 'btn btn-success']); ?>
        </td>
      </tr>
    <?php } ?>
  </tbody>
</table>
