<?php echo $this->getContent(); ?>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>File name</th>
      <th>Upload date</th>
      <th>Delivery date</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($data->items as $order) { ?>
    <tr>
      <td><?php echo $order->name; ?></td>
      <td><?php echo $order->file_name; ?></td>
      <td><?php echo date('d.m.Y', strtotime($order->upload_date)); ?></td>
      <td><?php echo $order->delivery_date; ?></td>
      <td colspan="3">
        <?php echo $this->tag->linkTo(['order/details/' . $order->id, 'Details', 'class' => 'btn btn-xs btn-default']); ?>
        <?php echo $this->tag->linkTo(['order/manage/' . $order->id . '/' . $order->ordered,
         ' Manage', 'class' => 'btn btn-xs btn-primary']); ?>
        <?php echo $this->tag->linkTo(['export/export/' . $order->id, ' Export', 'class' => 'btn btn-xs btn-success']); ?>
      </td>
    </tr>
  <?php } ?>
  </tbody>
</table>
