<?php echo $this->getContent(); ?>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <td>Customer order</td>
      <td>Type</td>
      <td>Quantity</td>
      <td>Barcode</td>
      <td colspan="2">Data</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($managedData as $itemKey => $item) { ?>
      <tr>
        <td><?php echo $item['customer_order']; ?></td>
        <td><?php echo $item['type']; ?></td>
        <td><?php echo $item['quantity']; ?></td>
        <td><?php echo $item['barcode']; ?></td>
        <td><?php echo $item['calculationData']['packing_info']; ?></td>
        <td><?php echo $item['calculationData']['total_leftover_quantity']; ?></td>
        <td>
          <?php echo $this->tag->linkTo([
            'export/exportSingle/' . $itemKey, ' Export', 'class' => 'btn btn-success'
          ]); ?>
        </td>
      </tr>
    <?php } ?>
  </tbody>
</table>
