<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Stiva</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='shortcut icon' href='<?php echo $this->url->getStatic('favicon.ico'); ?>' type='image/x-icon'>
    <?php $this->assets->outputCss(); ?>
  </head>
  <body>
    <?php echo $this->getContent(); ?>

    <?php $this->assets->outputJs(); ?>

    <script type="text/javascript">
      $('#order').on('change', function () {
        $('.form-file_value').text($(this).val());
      });

      $(document).ready(function() {
        $('[data-editable]').editable({
          mode: 'inline',
          url: $('[data-editable-url]').data('editable-url'),
          title: 'Enter new value',
          mode: 'inline',
        });

        var group = $('[data-sortable-table]').sortable({
          containerSelector: 'table',
          itemPath: '> tbody',
          itemSelector: 'tr',
          placeholder: '<tr class="placeholder"/>',
          group: 'serialization',
          onDragStart: function ($item, container, _super) {
            oldIndex = $item.index() + 1;
            $item.appendTo($item.parent());
            _super($item, container);
          },
          onDrop: function  ($item, container, _super) {
            var field;
            var newIndex = $item.index() + 1;

            if(newIndex != oldIndex) {
              var dataOrder = group.sortable("serialize").get();

              $.ajax({
                type: 'POST',
                url: $item.parent().data('sortable-url'),
                data: {
                  data: JSON.stringify(dataOrder)
                }
              });
            }

            _super($item, container);
          }
        });

      });
    </script>
  </body>
</html>
