<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>STIVA ;)</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='shortcut icon' href='<?php echo $this->url->getStatic('favicon.ico'); ?>' type='image/x-icon'/ >

    <?php $this->assets->outputCss(); ?>
  </head>
  <body>
    <?php echo $this->getContent(); ?>

    <?php $this->assets->outputJs(); ?>

<!-- todo: fix -->
<script>
  $('#order').on('change', function () {
    $('.form-file_value').text($(this).val());
  });
</script>


  </body>
</html>
