<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
          <?php echo $this->tag->linkTo(['index/index', 'STIVA', 'class' => 'navbar-brand']); ?>
        </div>
        <?php echo $this->elements->getMenu(); ?>
    </div>
</nav>

<div class="container">
    <?php echo $this->flash->output();

    echo $this->getContent(); ?>
    <hr>
    <footer>
        <p>Stiva&nbsp;&copy;&nbsp;<?php echo date("Y"); ?></p>
    </footer>
</div>
