<nav class="navbar navbar-default navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?php echo $this->tag->linkTo(['index/index', 'STIVA', 'class' => 'navbar-brand']); ?>
        </div>
        <?php echo $this->elements->getMenu(); ?>
    </div>
</nav>

<div class="container">
    <?php echo $this->flash->output();

    echo $this->getContent(); ?>
    <hr>
    <footer>
        <p>Stiva&nbsp;&copy;&nbsp;<?php echo date("Y"); ?></p>
    </footer>
</div>
